ClothBazar.Web/Controllers/ProductController.cs
using ClothBazar.Entities;
using ClothBazar.Services;
using ClothBazar.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothBazar.Web.Controllers
{
    public class ProductController : Controller
    {
        ProductsService productsService = new ProductsService();

        // GET: Product
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult ProductTable(string search)
        {

            var products = productsService.GetProducts();

            if (!string.IsNullOrEmpty(search)){
                products = products.Where(p=>p.Name != null && p.Name.ToLower().Contains(search.ToLower())).ToList();

            }

            
            return PartialView(products);
        }


        [HttpGet]
        public ActionResult Create()
        {
            CategoriesService categoriesService = new CategoriesService();
            var category = categoriesService.GetCategories();
            return PartialView(category);
        }

        [HttpPost]
        public ActionResult Create(CategoryViewModel model)
        {
            CategoriesService categoriesService = new CategoriesService();

            var newProduct = new Product();
            newProduct.Name = model.Name;
            newProduct.Description = model.Description;
            newProduct.Price = model.Price;
            newProduct.category = categoriesService.GetCategory(model.categoryID);
            
            productsService.SaveProduct(newProduct);
            return RedirectToAction("ProductTable");
        }


        [HttpGet]
        public ActionResult Edit(int ID)
        {
            var product = productsService.GetProduct(ID);
            return PartialView(product);
        }

        [HttpPost]
        public ActionResult Edit(Product product)
        {
            productsService.UpdateProduct(product);
            return RedirectToAction("ProductTable");
        }

        [HttpPost]
        public ActionResult Delete(int ID)
        {
            productsService.DeleteProduct(ID);

            return RedirectToAction("ProductTable");
        }
    }
}

ClothBazar.Web/Views/Product/Create.cshtml
@{
    ViewBag.Title = "Create";
}

@*<h2>Create Product</h2>*@

<div class="container">
    <form method="post" id="createProduct">
        <div class="form-group">
            <label>Name</label>
            <select class="form-control" name="categoryID">
                @foreach (var category in Model)
                {
                    <option value=@category.ID>@category.Name</option>
                }
            </select>
        </div>
        <div class="form-group">
            <label>Name</label>
            <input class="form-control" type="text" id="name" name="Name" />
        </div>
        <div class="form-group">
            <label>Description</label>
            <input type="text" id="description" name="Description" />
        </div>
        <div class="form-group">
            <label>Price</label>
            <input class="form-control" type="text" id="price" name="Price" />
        </div>
        <button id="saveBtn" class="btn btn-primary" type="button">SAVE</button>
    </form>
</div>





<script>

    $('#saveBtn').click(function () {

        //var name = $('#name').val();
        //var description = $('#description').val();
        //var price = $('#price').val();



        $.ajax(
            {
                type: "Post",
                url: "/Product/Create",
                //data: {
                //    Name: name,
                //    Description: description,
                //    Price: price
                //}
                data: $("#createProduct").serialize(),
            })
            .done(function (response) {
                $('#tableContainer').html(response);
                $('#actionContainer').html('');
            })
            .fail(function (data) {
                alert("failed");
            });
    });

</script>

ClothBazar.Web/Views/Product/Edit.cshtml
@model ClothBazar.Entities.Product
@{
    ViewBag.Title = "Edit";
}




<div class="container">
    <form method="post" id="editProduct">
        <label>id</label>
        <input type="number" id="id" name="id" value="@Model.ID" disabled/>
        <label>Name</label>
        <input type="text" id="name" name="Name" value="@Model.Name" />
        <label>Description</label>
        <input type="text" id="description" name="Description" value="@Model.Description" />
        <label>Price</label><input type="text" id="price" name="Price" value="@Model.Price" />
        <button id="updateBtn" type="button">Update</button>
    </form>
    </div>


    <script>

        $('#updateBtn').click(function () {

            //var name = $('#name').val();
            //var description = $('#description').val();
            //var price = $('#price').val();

            $.ajax(
                {
                    type: "Post",
                    url: "/Product/Edit",
                    //data: {
                    //    Name: name,
                    //    Description: description,
                    //    Price: price
                    //}
                    data: $("#editProduct").serialize(),
                })
                .done(function (response) {
                    $('#tableContainer').html(response);
                    $('#actionContainer').html('');
                })
                .fail(function (data) {
                    alert("failed");
                });
        });

    </script>

ClothBazar.Web/Views/Product/Index.cshtml
<style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" >
</style>

<div class="container-fluid">
    <div id="tableContainer">
        @{
            Html.RenderAction("ProductTable");
            <br />
            //Html.RenderAction("Create");
        }
    </div>
</div>

<br />
<hr />
<br />

<div id="actionContainer">
   
</div>

ClothBazar.Web/Views/Product/ProductTable.cshtml
@model List<ClothBazar.Entities.Product>
@Scripts.Render("~/bundles/jquery")
<script>
    https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js
</script>

<br />
<div class="title-section">
    <h2 class="title">Show Product</h2>
</div>
<br />


<div class="container">
    <form method="post" action="/Product/ProductTable">
        <div class="row">
            <div class="col-sm">
                <input type="search" id="searchText" />
            </div>
            <div class="col-sm">
                <button type="button" id="searchbtn">Search</button>
            </div>
        </div>
    </form>
    <br />

    <button id="newButton"><span class="fa fa-plus-circle"> &nbsp;</span>Add New Product</button>
</div>



   

<br />



    <div class="col-md-10 offset-md-1">

        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Category</th>
                    <th scope="col">Price</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th scope="row">*</th>
                        <td>@item.Name</td>
                        <td>
                            @if (item.category != null)
                            {
                                <text>@item.category.Name</text>
                            }
                            else
                            {
                                <text>-</text>
                            }
                        </td>
                        <td>@item.Price</td>
                        <td>
                            <button class="editBtn" data-id=@item.ID>Edit</button> &nbsp;
                            <button class="deleteBtn" data-id=@item.ID>Delete</button>&nbsp;
                            <button class="addToCart" data-id=@item.ID>Add To Cart</button>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>




    <script>

        $('#searchbtn').click(function () {
            var searchValue = $('#searchText').val();

            $.ajax(
                {
                    type: "Post",
                    url: '@Url.Action("ProductTable","Product")',
                    //"/Product/ProductTable",
                    data: {
                        search: searchValue
                    },
                })
                .done(function (response) {
                    $('#tableContainer').html(response);
                })
                .fail(function (data) {
                    alert("failed");
                });
        });



        $('#newButton').click(function () {

            $.ajax(
                {
                    type: "Get",
                    url: "/Product/Create",
                })
                .done(function (response) {
                    $('#actionContainer').html(response);
                    scrollToSection();
                })
                .fail(function (data) {
                    alert("failed");
                });
        });


        $('.editBtn').click(function () {
            $.ajax(
                {
                    type: "Get",
                    url: "/Product/Edit",
                    data: {
                        ID: $(this).attr('data-id'),
                    },
                })
                .done(function (response) {
                    $('#actionContainer').html(response);
                    scrollToSection();
                })
                .fail(function (data) {
                    console.log(data)
                    alert("failed");
                });
        });

        $('.deleteBtn').click(function () {

            swal({
                title: "Are you sure?",
                text: "",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {

                        $.ajax(
                            {
                                type: "Post",
                                url: "/Product/Delete",
                                data: {
                                    ID: $(this).attr('data-id'),
                                },
                            })
                            .done(function (response) {
                                console.log(response);
                                $('#tableContainer').html(response);
                                swal("Your file has been deleted!", {
                                    icon: "success",
                            })
                            .fail(function (data) {
                                console.log(data)
                                alert("failed");
                            });

                        
                        });
                    } 
                });
            
        });


        var products = [];
        $('.addToCart').click(function () {
            var productID = $(this).attr('data-id');
            products.push(productID);

            $.cookie('CartProduct', products.join('-'), { path: '/' });


        });



        function scrollToSection() {
            $('html, body').animate({
                scrollTop: $('#actionContainer').offset().top - 150
            }, 1000);
        }





        //$.ajax(
            //    {
            //        type: "Get",
            //        url: "",
            //        success: function () {

            //        },
            //        error: function () {

            //        }
            //    });


    </script>